services:
  - type: web
    name: locket-interaction-api
    env: docker
    region: singapore  # Choose appropriate region
    plan: free  # Or choose appropriate plan
    healthCheckPath: /health
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: FIREBASE_API_KEY
        sync: false
      - key: LOCKET_API_KEY
        sync: false